### ISSUE TITLE
Archive is likely invalid or corrupted when trying to extract old RPG Maker XP game.

### ISSUE THREAD

**Issue by vncastanheira** [uuksu/RPGMakerDecrypter#13] opened 2023-11-22 01:00 UTC
**Link to download the game/archive you're unable to decrypt**
Link to game: https://drive.google.com/file/d/1f7J8_OX7Rdwe0Poqjs1Sc7lO66X8kpmL/view?usp=sharing

**Describe the problem**
I'm trying to decript my RPG Maker XP game from 2008 but it's giving the "Something went wrong with reading or extraction. Archive is likely invalid or corrupted." error message. Tried both using the GUI and CLI executables, same error.
I have vague memory of this having some encryption, although I'm not sure, it has been a long time.

**Details (please complete the following information):**
 - OS: Windows 10
 - RPGMakerDecrypter version: v2.0.13

**Screenshots**
![RPGMakerDecrypter_FQECt8pouW](https://github.com/uuksu/RPGMakerDecrypter/assets/1210284/b9892361-1544-414d-a6f4-7896ab1a43b4)

**Comment by uuksu** [comment] 2023-12-13 13:45
Hey and sorry for taking far too long to answer.

I just tested decryption with the latest version (v2.0.13) and for me it works. I was able to decrypt your game:

![DecryptedGame](https://github.com/uuksu/RPGMakerDecrypter/assets/8851723/996eaf2d-8dff-4853-b7cb-3125cd82cf25)

It's interesting why you're unable to decrypt the game. I'm suspecting that it has something to do with your environment that I'm unable to reproduce.  Error saying that the archive is likely corrupted is unfortunately pretty bad and it can be actually something else that creates the error.

Would you mind trying this special version I compiled just for you that has the actual error logging enabled. You should see more specific error on the CLI and if you could copy the line for me to inspect?

https://uuksu.fi/other/RPGMakerDecrypter/RPGMakerDecrypter-2.0.13-temp-logging.zip

**Comment by vncastanheira** [comment] 2023-12-15 17:23
Hey, after seeing your post I copied the .rgssad file to my Desktop folder and it worked. Tried it again with the CLI you just compiled and now I know what happened.

I was trying to decompile the game while located on "C:\Program Files (x86)" folder, so it wasn't because of corruption but rather lack of admin priviledge.

![image](https://github.com/uuksu/RPGMakerDecrypter/assets/1210284/8484931a-fa88-4876-b4a6-1f3ce8f9831d)

**Comment by uuksu** [comment] 2023-12-20 11:17
I'm glad it worked out for you and now we know what the problem was. I think I should make the error less generic and maybe even add logging to a file that could be easily attached here when creating a new issue (if more error situations like this end up happening). I'm going to leave your issue open and close it when these have been implemented. Thank you for helping me here!

Free and open-source is always better, atleast that is what I think ;)

**Comment by uuksu** [comment] 2024-01-15 12:30
This has been implemented in v2.0.14. Thank you!

**Closed by uuksu** 2024-01-15 12:30 UTC
